AWSTemplateFormatVersion: '2010-09-09'
Description: Roles and Policies Stack

Resources:
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DeploymentRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"

Outputs:
  DeploymentRoleArn:
    Description: The ARN of the Deployment Role
    Value: !GetAtt DeploymentRole.Arn
    