name: mexc-futures-listing-notifier-deployment

on:
  push:
    branches:
      - main

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  AWS_REGION: eu-central-1

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up AWS CLI
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-to-assume: ${{ env.AWS_ROLE_ARN }}
#           aws-region: eu-central-1

#       - name: Deploy CloudFormation stack
#         run: |
#           aws cloudformation deploy \
#             --template-file aws_infra/roles_and_policies.yaml \
#             --stack-name mexc-futures-listing-notifier-roles-and-policies \
#             --capabilities CAPABILITY_NAMED_IAM
