name: mexc-futures-listing-notifier-deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-deployment-session
          aws-region: eu-central-1
          
      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://aws_infra/roles_and_policies.yaml
            
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file aws_infra/roles_and_policies.yaml \
            --stack-name mexc-futures-listing-notifier-roles-and-policies \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset